### ISSUE TITLE
Cannot save changes on latest builds

### ISSUE THREAD

**Issue by kurzninja** [Seeed-Studio/seeed-linux-openwrt#33] opened 2022-07-13 16:59 UTC
With the latest builds I am able to install and boot, but suddenly I cannot get the LuCI web interface to "save and apply" changes. Clicking the button looks as if it's saving, but goes right back to saying there are unsaved changes and rebooting the router makes the changes go away. Anyone else have a problem like this?

**Comment by blockheadgittyup** [comment] 2022-07-25 20:48
This is true for me also. It is not usually after the first power cycle but usually within 5 the partition switches to read only and no further changes can be made.
![image](https://user-images.githubusercontent.com/109991937/180871270-7c40c382-f346-46c7-bb46-7e708eba5ac2.png)

**Comment by kurzninja** [comment] 2022-07-26 04:20
Glad to know it's not just me.

**Comment by blockheadgittyup** [comment] 2022-07-26 17:20
It would be better to know if a developer sees this and can help.... Anyone?

**Comment by lakshanthad** [comment] 2022-07-26 17:57
Hello,

Could you please enter the following on a terminal window of the device and reboot?

```sh
e2fsck -p /dev/mmcblk0p2
```

**Comment by blockheadgittyup** [comment] 2022-07-26 19:42
This does change it back to rw, thanks. I am guessing this doesn't fix the root cause, is that correct?

**Comment by lakshanthad** [comment] 2022-07-26 19:46
That's great!

Can you turn off the power directly (without shutdown command) and turn it back on to see whether the issue comes back again?

**Comment by kurzninja** [comment] 2022-07-26 22:12
I ran the command and was able to make and save changes, then I physically power cycled the router and tried again and now Save and Apply is no longer working again. The file system rw switch does not appear to survive rebooting.

**Comment by lakshanthad** [comment] 2022-07-27 02:56
So it seems that the issue happens only when you physically power cycle the router. Correct?

Does running the command I mentioned and rebooting the system always worked to solve the problem?

**Comment by blockheadgittyup** [comment] 2022-07-27 13:41
So After 5 power cycles the problem reoccurred for me. Yes, the command fixed it again.

**Comment by kurzninja** [comment] 2022-07-29 15:37
> So it seems that the issue happens only when you physically power cycle the router. Correct?
> 
> Does running the command I mentioned and rebooting the system always worked to solve the problem?

To my knowledge, it also happens if I software reboot the router, not just physically power cycle it. I would have to do some specific testing.

**Comment by LynnL4** [comment] 2023-03-02 03:21
Close it, then discuss it here https://github.com/Seeed-Studio/seeed-linux-openwrt/issues/38

**Closed by LynnL4** 2023-03-02 03:21 UTC
Labels: bug
